spring.application.name=market-stream
spring.kafka.bootstrap-servers=localhost:9092

# --- PRODUTOR (Envia dados) ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Adiciona o cabeçalho de tipo para o JSON não se perder
spring.kafka.producer.properties.spring.json.add.type.headers=true

# --- CONSUMIDOR (Recebe dados) ---
spring.kafka.consumer.group-id=market-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Permite que o Kafka transforme o JSON de volta para qualquer classe do seu projeto
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# --- REDIS (Salva o estado atual) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379